sudo: required
language: cpp
cache: ccache
python: 3.6
git:
    depth: 3
matrix:
    fast_finish: true
    include:
        - os: linux
          compiler: emcc
          install:
              # setup emscripten
              - git clone --depth 1 --branch incoming https://github.com/urho3d/emscripten-sdk.git ~/emscripten-sdk
              - ~/emscripten-sdk/emsdk activate --build=Release sdk-incoming-64bit binaryen-master-64bit
              - source ~/emscripten-sdk/emsdk_env.sh
              - for compiler in $EMSCRIPTEN/{emcc,em++}; do touch -d "2017-01-01 00:00:00 +0800" $compiler; done
          script:
              - mkdir build
              - cd build
              - emcmake cmake -D DESKTOP=NO -D WEB=YES -D CMAKE_BUILD_TYPE=Release $TRAVIS_BUILD_DIR
              - make
          before_deploy:
              # prepare website
              - mv vipster.{js,wasm} $TRAVIS_BUILD_DIR/gh-pages/emscripten
          deploy:
              - provider: pages
                skip_cleanup: true
                github_token: $GH_TOKEN
                local_dir: $TRAVIS_BUILD_DIR/gh-pages
                on:
                    branch: master

        - os: linux
          compiler: gcc
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                      - sourceline: "ppa:beineri/opt-qt-5.10.1-trusty"
                  packages:
                      - python-dev
                      - g++-5
                      - qt510-meta-minimal
                      - qt510script
          install:
              - pyenv shell 3.6
              # GCC5:
              - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
              - sudo update-alternatives --set gcc /usr/bin/gcc-5
          script:
              # build debug-version
              - mkdir build
              - cd build
              - cmake -D PYTHON=YES -D TESTS=YES -D CMAKE_BUILD_TYPE=Debug $TRAVIS_BUILD_DIR
              - make
              # run tests
              - ./test_lib
          after_success:
              # get coverage
              - bash <(curl -s https://codecov.io/bash) -R $TRAVIS_BUILD_DIR -x gcov-5
          before_deploy:
              # build release-version
              - cd -
              - mkdir release
              - cd release
              - cmake -D PYTHON=YES -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr $TRAVIS_BUILD_DIR
              - make DESTDIR=AppDir install
              # fill AppDir with dependencies
              - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" -O linuxdeployqt
              - chmod +x linuxdeployqt
              - ./linuxdeployqt AppDir/usr/share/applications/vipster.desktop -bundle-non-qt-libs;
              # bundle libstdc++ to be compatible with older linuxes, see https://github.com/darealshinji/AppImageKit-checkrt
              - mkdir -p AppDir/usr/optional/libstdc++
              - wget -c https://github.com/darealshinji/AppImageKit-checkrt/releases/download/continuous/exec-x86_64.so -O AppDir/usr/optional/exec.so
              - cp /usr/lib/x86_64-linux-gnu/libstdc++.so.6 AppDir/usr/optional/libstdc++/
              # use custom AppRun so we get the correct working directory
              - rm AppDir/AppRun
              - cp $TRAVIS_BUILD_DIR/dist/AppRun AppDir
              - chmod a+x AppDir/AppRun
              # create AppImage
              - wget -c https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool
              - chmod +x appimagetool
              - ./appimagetool -g AppDir $TRAVIS_BUILD_DIR/Vipster-x86_64.AppImage
          deploy:
              - provider: releases
                skip_cleanup: true
                api_key:
                    secure: KBiyKkeDNQQE7m1WI0s9+YRTiO9eAAYZTljTrTMWicKWRo28NNNGaeZ5DYZ0J0CCnJAaywIPBHsfcis10rLyIB+GYyVN6oToI/OZf/aufLry4zbmiB/LQva4zln6zQAj/SIxUVRzu6rG30s+imAxUzbIboAHD068yTKpd3A/IMDCutI1OZZ4TPFb4fUZauDvGn3j30fty13OyRs3aEyCd7ldHxydnMPJsOZfp26KTPokWItUnXrfhv7igjRPRHu3DAoxhZBO3gWbPrT0QAUP59bD4A97PXpXVyqiE7A6vK4jvbYCuYsbEyCj2HT4QZ2OLGt9MEo4+/4C0almNd9FUYwXKK9jZmfqSQfc1EWmBJCQ+ABtIIxExbXs6V6tsfYxcAxU1NC8jaMFwIe4sX67eKP5IUE2/wmlqxGIaTH3Lm3S7HzyNHMlrLPdEh4csoo+V2ljmIDCav02huKv5DixLUfN5olESb0xgyU8iOiEOrA2P2uCDfKsdbOkwJHvHKgZx/Y93ysa5Z1X5NKgAoMzYBXWVihOwa93MRxWyTWxFZKzolhFzCBH2+VWCwhLKJ9+rpLC5z1zipidzHC3/yWtFK6BZ2GSlDW20uQGWMWc88Wyp+JFVYqXHG4RF7veM2+s2vxlNzHqBACK7S6CNk2ffbbAJC9amdzKIKrBDAvw0ko=
                file: $TRAVIS_BUILD_DIR/Vipster-x86_64.AppImage
                draft: true
                on:
                    tags: true

        - os: osx
          osx_image: xcode10
          script:
              - brew update
              - brew install qt
              - mkdir build
              - cd build
              - cmake -D CMAKE_PREFIX_PATH=/usr/local/opt/qt -D TESTS=YES -D CMAKE_BUILD_TYPE=Release $TRAVIS_BUILD_DIR
              - make
              - ./test_lib
          deploy:
              - provider: releases
                api_key:
                    secure: KBiyKkeDNQQE7m1WI0s9+YRTiO9eAAYZTljTrTMWicKWRo28NNNGaeZ5DYZ0J0CCnJAaywIPBHsfcis10rLyIB+GYyVN6oToI/OZf/aufLry4zbmiB/LQva4zln6zQAj/SIxUVRzu6rG30s+imAxUzbIboAHD068yTKpd3A/IMDCutI1OZZ4TPFb4fUZauDvGn3j30fty13OyRs3aEyCd7ldHxydnMPJsOZfp26KTPokWItUnXrfhv7igjRPRHu3DAoxhZBO3gWbPrT0QAUP59bD4A97PXpXVyqiE7A6vK4jvbYCuYsbEyCj2HT4QZ2OLGt9MEo4+/4C0almNd9FUYwXKK9jZmfqSQfc1EWmBJCQ+ABtIIxExbXs6V6tsfYxcAxU1NC8jaMFwIe4sX67eKP5IUE2/wmlqxGIaTH3Lm3S7HzyNHMlrLPdEh4csoo+V2ljmIDCav02huKv5DixLUfN5olESb0xgyU8iOiEOrA2P2uCDfKsdbOkwJHvHKgZx/Y93ysa5Z1X5NKgAoMzYBXWVihOwa93MRxWyTWxFZKzolhFzCBH2+VWCwhLKJ9+rpLC5z1zipidzHC3/yWtFK6BZ2GSlDW20uQGWMWc88Wyp+JFVYqXHG4RF7veM2+s2vxlNzHqBACK7S6CNk2ffbbAJC9amdzKIKrBDAvw0ko=
                file: default/install-root/Vipster-OSX.dmg
                skip_cleanup: true
                draft: true
                on:
                    tags: true
