sudo: required
language: cpp
cache: ccache
git:
    depth: 3
matrix:
    fast_finish: true
    include:
        - os: linux
          compiler: gcc
          python: 3.6
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                      - sourceline: "ppa:beineri/opt-qt-5.10.1-trusty"
                  packages:
                      - python-dev
                      - g++-5
                      - qt510-meta-minimal
                      - qt510script
          before_install:
              # Toolchains:
              - git clone --depth 1 --branch incoming https://github.com/urho3d/emscripten-sdk.git ~/emscripten-sdk
              - ~/emscripten-sdk/emsdk activate --build=Release sdk-incoming-64bit binaryen-master-64bit
              - source ~/emscripten-sdk/emsdk_env.sh
              - for compiler in $EMSCRIPTEN/{emcc,em++}; do touch -d "2017-01-01 00:00:00 +0800" $compiler; done
              - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
              - sudo update-alternatives --set gcc /usr/bin/gcc-5
              # Qt:
              - QT_ENV_SCRIPT=$(find /opt -name 'qt*-env.sh')
              - source $QT_ENV_SCRIPT
              # Qbs:
              - git clone --depth 1 -b v1.11.0 https://code.qt.io/qbs/qbs.git qbs-build
              - pushd qbs-build
              - qmake -r qbs.pro "CONFIG+=qbs_no_dev_install qbs_no_man_install" && make
              - export PATH=$PATH:$PWD/bin
              - popd
              - qbs setup-toolchains `which g++` gcc
              - qbs setup-qt `which qmake` qt-gcc
              - qbs config profiles.qt-gcc.baseProfile gcc
          install:
              - cd ~
              # GCC
              # pretty sure travis' python2 sysconfig-module is broken, force python3
              - qbs build -f $TRAVIS_BUILD_DIR config:gcc profile:qt-gcc qbs.buildVariant:profile project.pythonBuild:true project.pythonName:"python3"
              # EMSCRIPTEN
              - qbs build -f $TRAVIS_BUILD_DIR config:emscripten profile:emscripten project.webBuild:true qbs.buildVariant:release
          script:
              # GCC
              - cd ~
              - qbs run --products test_libvipster config:gcc
          after_success:
              # get coverage
              - cd ~/gcc
              - bash <(curl -s https://codecov.io/bash) -R $TRAVIS_BUILD_DIR -x gcov-5
          before_deploy:
              - mv ~/emscripten/install-root $TRAVIS_BUILD_DIR/gh-pages/emscripten
              - cd $TRAVIS_BUILD_DIR
          deploy:
              - provider: pages
                skip_cleanup: true
                github_token: $GH_TOKEN
                local_dir: gh-pages
                on:
                    branch: master
        - os: osx
          before_install:
              - brew update
              - brew install qbs
              - qbs setup-toolchains --detect
              - qbs setup-qt /usr/local/opt/qt/bin/qmake qt-brew
              - qbs config profiles.qt-brew.baseProfile xcode-macosx-x86_64
          install:
              - cd ~
              - qbs build -f $TRAVIS_BUILD_DIR qbs.buildVariant:release profile:qt-brew
          script:
              - cd ~
              - qbs run --products test_libvipster
          before_deploy:
              - cd ~
              - qbs resolve project.macInstall:true
              - qbs build
          deploy:
              - provider: releases
                github_token: $GH_TOKEN
                file: default/install-root/Vipster.dmg
                skip_cleanup: true
                draft: true
