sudo: require
dist: trusty
language: cpp
compiler: gcc
before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo add-apt-repository --yes ppa:beineri/opt-qt571-trusty
    - sudo apt-get update -qq
    - sudo pip install codecov
    - sudo apt-get install -qq -y g++-5 qt57-meta-minimal
    - QT_ENV_SCRIPT=$(find /opt -name 'qt*-env.sh')
    - source $QT_ENV_SCRIPT
    - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
    - wget http://mirrors.kernel.org/ubuntu/pool/main/b/boost1.62/libboost1.62-dev_1.62.0+dfsg-4_amd64.deb
    - sudo dpkg -i libboost1.62-dev_1.62.0+dfsg-4_amd64.deb
    - wget http://mirrors.kernel.org/ubuntu/pool/universe/p/pybind11/pybind11-dev_2.0.1-1_all.deb
    - sudo dpkg -i pybind11-dev_2.0.1-1_all.deb
install:
    - qmake -r CONFIG+=debug QMAKE_CXX=g++-5 QMAKE_LINK=g++-5 QMAKE_CC=gcc-5 QMAKE_CXXFLAGS+=-std=c++1y
    - make
    - cp libvipster/default.json ~/.vipster.json
script:
    - LD_LIBRARY_PATH=libvipster tests/tst_libvipstertest
after_success:
    - ./get_code_cov.sh
    - codecov
