sudo: require
language: cpp
git:
    depth: 3
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
            - sourceline: "ppa:beineri/opt-qt-5.10.1-trusty"
        packages:
            - g++-5
            - clang-3.7
            - qt57-meta-minimal
before_install:
    # Compilers:
    - alias clang=clang-3.7
    - alias clang++=clang++-3.7
    # Emscripten:
    - git clone --depth 1 --branch incoming https://github.com/urho3d/emscripten-sdk.git ~/emscripten-sdk
    - ~/emscripten-sdk/emsdk activate --build=Release sdk-incoming-64bit binaryen-master-64bit
    - source ~/emscripten-sdk/emsdk_env.sh
    - for compiler in $EMSCRIPTEN/{emcc,em++}; do touch -d "2017-01-01 00:00:00 +0800" $compiler; done
    # Qt:
    - QT_ENV_SCRIPT=$(find /opt -name 'qt*-env.sh')
    - source $QT_ENV_SCRIPT
    - qbs setup-toolchains `which clang` clang
    - qbs setup-qt `which qmake` qt-clang
    - qbs config profiles.qt-clang.baseProfile clang
    - qbs setup-toolchains `which gcc` gcc
    - qbs setup-qt `which qmake` qt-gcc
    - qbs config profiles.qt-gcc.baseProfile gcc
    # Target folders:
    - mkdir ~/gcc ~/clang ~/emscripten
install:
    # GCC
    - cd ~/gcc
    - qbs build -f $TRAVIS_BUILD_DIR profile:qt-gcc qbs.buildVariant:profile
    # CLANG
    - cd ~/clang
    - qbs build -f $TRAVIS_BUILD_DIR profile:qt-clang
    # EMSCRIPTEN
    - cd ~/emscripten
    - qbs build -f $TRAVIS_BUILD_DIR profile:emscripten
script:
    # GCC
    - cd ~/gcc
    - qbs run --products test_libvipster
    # CLANG
    - cd ~/clang
    - qbs run --products test_libvipster
after_success:
    # get coverage
    - cd ~/gcc
    - bash <(curl -s https://codecov.io/bash) -R $TRAVIS_BUILD_DIR -x gcov-5
before_deploy:
    - mv ~/emscripten/install-root $TRAVIS_BUILD_DIR/gh-pages/emscripten
    - cd $TRAVIS_BUILD_DIR
deploy:
    - provider: pages
      skip_cleanup: true
      github_token: $GH_TOKEN
      local_dir: gh-pages
      on:
          branch: testing
