sudo: require
dist: trusty
language: cpp
compiler: gcc
before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo add-apt-repository --yes ppa:beineri/opt-qt571-trusty
    - sudo apt-get update -qq
    - sudo pip install codecov
    - sudo apt-get install -qq -y g++-5 qt57-meta-minimal
    - QT_ENV_SCRIPT=$(find /opt -name 'qt*-env.sh')
    - source $QT_ENV_SCRIPT
    - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
    - wget https://github.com/pybind/pybind11/archive/v2.1.1.tar.gz
    - tar -xf v2.1.1.tar.gz
    - wget https://dl.bintray.com/boostorg/release/1.64.0/source/boost_1_64_0.tar.bz2
    - tar -xf boost_1_64_0.tar.bz2
install:
    - qmake -r CONFIG+=debug QMAKE_CXX=g++-5 QMAKE_LINK=g++-5 QMAKE_CC=gcc-5 QMAKE_CXXFLAGS+=-std=c++1y INCLUDEPATH+=$TRAVIS_BUILD_DIR/boost_1_64_0 INCLUDEPATH+=$TRAVIS_BUILD_DIR/pybind11-2.1.1/include
    - make
    - cp libvipster/default.json ~/.vipster.json
script:
    - LD_LIBRARY_PATH=libvipster tests/tst_libvipstertest
after_success:
    - ./get_code_cov.sh
    - codecov
