version: 1.0.{build}
clone_depth: 30
clone_folder: c:\projects\vipster
environment:
  QTDIR: C:\Qt\5.10.1\mingw53_32
  MWDIR: C:\Qt\Tools\mingw530_32\bin
  PATH: '%QTDIR%\lib;%QTDIR%\bin;%MWDIR%;C:\projects\vipster\libvipster\release;%PATH%'
install:
    - choco install -y qbs --version 1.10.1
build_script:
    - qbs.exe setup-toolchains --type mingw %MWDIR%\g++.exe gcc
    - qbs.exe setup-qt %QTDIR%\bin\qmake.exe qt-gcc
    - qbs.exe build release profile:qt-gcc products.test_libvipster.qbsfix:true
test_script:
    - qbs.exe run --products test_libvipster release
after_test:
    - ps: |
        if ($env:APPVEYOR_REPO_TAG -eq "true") {
            Remove-Item release\install-root\test_libvipster.exe
            qbs.exe resolve project.winInstall:true release
            qbs.exe build release
        }
artifacts:
    - name: Installer
      path: 'release\Vipster-Win-32-install.exe'
    - name: Archive
      path: 'release\Vipster-Win-32.zip'
deploy:
    - provider: Github
      release: Vipster %APPVEYOR_REPO_TAG_NAME%
      auth_token:
        secure: B7byrQs5wuFQdK1ws3GCmTGI/0YCLZ3TUN+h3UxP9nl/uOlZX1jS1kO+AMWhprA5
      draft: true
      artifacts: /.*\.(exe|7z)/
      on:
        branch: master
        appveyor_repo_tag: true
