version: 1.0.{build}
clone_depth: 30
clone_folder: c:\projects\vipster
environment:
  QTDIR: C:\Qt\5.10.1\mingw53_32
  MWDIR: C:\Qt\Tools\mingw530_32\bin
  PATH: '%QTDIR%\lib;%QTDIR%\bin;%MWDIR%;C:\projects\vipster\libvipster\release;%PATH%'
install:
    - choco install -y qbs --version 1.11.0
build_script:
    - qbs.exe setup-toolchains --type mingw %MWDIR%\g++.exe gcc
    - qbs.exe setup-qt %QTDIR%\bin\qmake.exe qt-gcc
    - qbs.exe build config:release profile:qt-gcc project.winInstall:true modules.nsis.toolchainInstallPath:"C:\Program Files (x86)\NSIS"
test_script:
    - qbs.exe run --products test_libvipster config:release
artifacts:
    - name: Installer
      path: 'release\Vipster-Win-32-install.exe'
    - name: Archive
      path: 'release\Vipster-Win-32.zip'
deploy:
    - provider: GitHub
      auth_token:
        secure: B7byrQs5wuFQdK1ws3GCmTGI/0YCLZ3TUN+h3UxP9nl/uOlZX1jS1kO+AMWhprA5
      draft: true
      artifacts: /.*\.(exe|7z)/
      on:
        branch: master
        appveyor_repo_tag: true
